# Generated by Django 4.2.3 on 2023-07-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
